/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    _editor: typeof import('./../components/old/views/masm/_editor.vue')['default']
    _TheHeader: typeof import('./../components/old/views/layout/_TheHeader.vue')['default']
    _TheLogin: typeof import('./../components/old/views/user/_TheLogin.vue')['default']
    '[id]': typeof import('./../components/old/views/map/[thread]/[id].vue')['default']
    ActionChangeMode: typeof import('./../components/old/views/map/components/ActionChangeMode.vue')['default']
    ActionCopy: typeof import('./../components/old/views/map/components/ActionCopy.vue')['default']
    ActionDetail: typeof import('./../components/old/views/map/components/ActionDetail.vue')['default']
    ActionDownload: typeof import('./../components/old/views/map/components/ActionDownload.vue')['default']
    ActionUpload: typeof import('./../components/old/views/map/components/ActionUpload.vue')['default']
    ColorizeSpan: typeof import('./../components/old/components/ColorizeSpan.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIconDocumentCopy: typeof import('@element-plus/icons-vue')['DocumentCopy']
    ElIconDownload: typeof import('@element-plus/icons-vue')['Download']
    ElIconMore: typeof import('@element-plus/icons-vue')['More']
    ElIconOrange: typeof import('@element-plus/icons-vue')['Orange']
    ElIconPlus: typeof import('@element-plus/icons-vue')['Plus']
    ElIconUpload: typeof import('@element-plus/icons-vue')['Upload']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Map: typeof import('./../components/old/views/map.vue')['default']
    MapList: typeof import('./../components/old/views/map/components/MapList.vue')['default']
    Masm: typeof import('./../components/old/views/masm.vue')['default']
    NavUserInfo: typeof import('./../components/NavUserInfo.vue')['default']
    PageHeader: typeof import('./../components/old/components/PageHeader.vue')['default']
    SquaredImage: typeof import('./../components/old/components/SquaredImage.vue')['default']
    Upload: typeof import('./../components/old/views/map/upload.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
