// noinspection SpellCheckingInspection

const Vars = {
    this: variable("@this"),
    thisX: variable("@thisx"),
    thisY: variable("@thisy"),
    unit: variable("@unit"),

    ipt: variable("@ipt"),
    counter: variable("@counter"),
    links: variable("@links"),
    time: variable("@time"),
    tick: variable("@tick"),
    mapW: variable("@mapw"),
    mapH: variable("@maph"),
}

const Items = {
    copper: variable("@copper"),
    lead: variable("@lead"),
    metaglass: variable("@metaglass"),
    graphite: variable("@graphite"),
    sand: variable("@sand"),
    coal: variable("@coal"),
    titanium: variable("@titanium"),
    thorium: variable("@thorium"),
    scrap: variable("@scrap"),
    silicon: variable("@silicon"),
    plastanium: variable("@plastanium"),
    phaseFabric: variable("@phase-fabric"),
    surgeAlloy: variable("@surge-alloy"),
    sporePod: variable("@spore-pod"),
    blastCompound: variable("@blast-compound"),
    pyratite: variable("@pyratite"),
}

const Units = {
    dagger: variable("@dagger"),
    mace: variable("@mace"),
    fortress: variable("@fortress"),
    scepter: variable("@scepter"),
    reign: variable("@reign"),
    nova: variable("@nova"),
    pulsar: variable("@pulsar"),
    quasar: variable("@quasar"),
    vela: variable("@vela"),
    corvus: variable("@corvus"),
    crawler: variable("@crawler"),
    atrax: variable("@atrax"),
    spiroct: variable("@spiroct"),
    arkyid: variable("@arkyid"),
    toxopid: variable("@toxopid"),
    flare: variable("@flare"),
    horizon: variable("@horizon"),
    zenith: variable("@zenith"),
    antumbra: variable("@antumbra"),
    eclipse: variable("@eclipse"),
    mono: variable("@mono"),
    poly: variable("@poly"),
    mega: variable("@mega"),
    quad: variable("@quad"),
    oct: variable("@oct"),
    risso: variable("@risso"),
    minke: variable("@minke"),
    bryde: variable("@bryde"),
    sei: variable("@sei"),
    omura: variable("@omura"),
    retusa: variable("@retusa"),
    oxynoe: variable("@oxynoe"),
    cyerce: variable("@cyerce"),
    aegires: variable("@aegires"),
    navanax: variable("@navanax"),
    alpha: variable("@alpha"),
    beta: variable("@beta"),
    gamma: variable("@gamma")
}

const Sensor = {
    totalItems: variable("@totalItems"),
    firstItem: variable("@firstItem"),
    totalLiquids: variable("@totalLiquids"),
    totalPower: variable("@totalPower"),
    itemCapacity: variable("@itemCapacity"),
    liquidCapacity: variable("@liquidCapacity"),
    powerCapacity: variable("@powerCapacity"),
    powerNetStored: variable("@powerNetStored"),
    powerNetCapacity: variable("@powerNetCapacity"),
    powerNetIn: variable("@powerNetIn"),
    powerNetOut: variable("@powerNetOut"),
    ammo: variable("@ammo"),
    ammoCapacity: variable("@ammoCapacity"),
    health: variable("@health"),
    maxHealth: variable("@maxHealth"),
    heat: variable("@heat"),
    efficiency: variable("@efficiency"),
    progress: variable("@progress"),
    timescale: variable("@timescale"),
    rotation: variable("@rotation"),
    x: variable("@x"),
    y: variable("@y"),
    shootX: variable("@shootX"),
    shootY: variable("@shootY"),
    size: variable("@size"),
    dead: variable("@dead"),
    range: variable("@range"),
    shooting: variable("@shooting"),
    boosting: variable("@boosting"),
    mineX: variable("@mineX"),
    mineY: variable("@mineY"),
    mining: variable("@mining"),
    team: variable("@team"),
    type: variable("@type"),
    flag: variable("@flag"),
    controlled: variable("@controlled"),
    controller: variable("@controller"),
    commanded: variable("@commanded"),
    name: variable("@name"),
    payloadCount: variable("@payloadCount"),
    payloadType: variable("@payloadType"),
    enabled: variable("@enabled"),
    config: variable("@config"),
}